image:
  file: .gitpod/Dockerfile
tasks:
  - name: Build
    init: |
      mvn clean package -PbuildKar
      gp sync-done build

  - name: Nexus-/Crowd-Server
    init: |
      gp sync-await build
    command: |
      docker-compose up 

  - name: Init-Nexus-PW
    init: |
      gp sync-await build
      sleep 120
      echo "Credentials to login into nexus"
      echo "User     : admin"
      echo "Password : $(docker exec -it nexus /bin/bash -c 'while [ ! -f /nexus-data/admin.password ]; do sleep 5; done; cat /nexus-data/admin.password')"
