volumes:
  nexus-data:
  crowd-data:

services:
  nexus:
    build: .
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
  crowd:
    image: atlassian/crowd
    container_name: crowd
    ports:
      - "8095:8095"
    volumes:
      - crowd-data:/var/atlassian/application-data/crowd