FROM sonatype/nexus3:${nexus-docker.version}

USER root

# Add nexus-crowd-plugin
COPY target/nexus3-crowd-plugin-0-SNAPSHOT-bundle.kar /opt/sonatype/nexus/deploy
COPY target/etc/crowd.properties /opt/sonatype/nexus/etc/crowd.properties

# setup permissions
RUN chown nexus:nexus -R /opt/sonatype/nexus

USER nexus