name: Build

on:
  push:
    branches: [ master-frimtec ]
  pull_request:
    branches: [ master-frimtec ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Build with Maven
        run: mvn clean package -PbuildKar

      - name: Test coverage Report
        run: mvn jacoco:prepare-agent test jacoco:report

      - uses: codecov/codecov-action@v3.1.4

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nexus3-crowd-plugin-bundle.kar
          path: ./target/nexus3-crowd-plugin-0-SNAPSHOT-bundle.kar
