name: Build

on:
  push:
    branches: [ master-frimtec ]
  pull_request:
    branches: [ master-frimtec ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 17
          maven-version: 3.9.9

      - name: Verify Maven version
        run: mvn --version

      - name: Build with Maven
        run: mvn clean package -PbuildKar

      - name: Test coverage Report
        run: mvn jacoco:prepare-agent test jacoco:report

      - uses: codecov/codecov-action@v5.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}      

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexus3-crowd-plugin-bundle.kar
          path: ./target/nexus3-crowd-plugin-0-SNAPSHOT-bundle.kar
