name: Deploy release

on:
  release:
    types: [prereleased, released]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.17.0
        with:
          java-version: 11
          maven-version: 3.9.9

      - name: Verify Maven version
        run: mvn --version

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set pom version
        run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Build with Maven
        run: mvn clean package -PbuildKar

      - name: Upload kar bundle
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/nexus3-crowd-plugin-${{ steps.get_version.outputs.VERSION }}-bundle.kar
          asset_name: nexus3-crowd-plugin-${{ steps.get_version.outputs.VERSION }}-bundle.kar
          asset_content_type: application/octet-stream
